name: Build rounded Docker icon
on:
  workflow_dispatch:
  push:
    paths:
      - docker-icon.png

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick pngquant

      - name: Make round & compress
        shell: bash
        run: |
          set -euo pipefail
          SRC="docker-icon.png"
          mkdir -p icons

          convert "$SRC" -resize 1024x1024 -gravity center -background none -extent 1024x1024 \
            \( -size 1024x1024 xc:none -fill white -draw "circle 512,512 512,0" \) \
            -alpha off -compose copy_opacity -composite icons/icon-1024.png

          convert icons/icon-1024.png -resize 512x512 icons/icon-512.png
          convert icons/icon-1024.png -resize 256x256 icons/icon-256.png

          pngquant --force --strip --quality=75-90 --output icons/icon-1024.png icons/icon-1024.png || true
          pngquant --force --strip --quality=75-90 --output icons/icon-512.png  icons/icon-512.png  || true
          pngquant --force --strip --quality=75-90 --output icons/icon-256.png  icons/icon-256.png  || true

      - name: Commit icons
        run: |
          git config user.name  "icon-bot"
          git config user.email "icon-bot@users.noreply.github.com"
          git add icons/
          git commit -m "Generate rounded icons" || echo "No changes"
          git push
